name: Sync

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          DST_TOKEN:  ${{ secrets.GITEE_TOKEN }}
      with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: "git@github.com:piggy0915/axure.git"
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: "git@gitee.com:piggy0915/axure.git"
          # 启用后会显示所有执行命令
          #debug: true  
          # 启用后，强制同步，即强制覆盖目的端仓库
          #force_update: true 
          # git超时设置，超时后会自动重试git操作
          #timeout: '600s'            


    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@master
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: piggy0915
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库
          gitee-repo: piggy0915/axure